version: "3.7"

services:
  postgre:
    container_name: postgre_sql
    build: postgre
    volumes:
      - ./postgre/postgre_database:/var/lib/postgresql/data
    ports:
      - ${POSTGRE_PORT}:5432
    restart: unless-stopped

  pgadmin:
    container_name: pg_admin
    build: pgadmin 
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./pgadmin/pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  mongo:
    container_name: mongo
    build: mongo 
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo/mongo_database:/var/lib/mongo/data
    restart: unless-stopped
  